export const industries = [
  'Agency or Sales House',
  'Agriculture',
  'Art and Design',
  'Automotive',
  'Construction',
  'Consulting',
  'Consumer Packaged Goods',
  'Education',
  'Engineering',
  'Entertainment',
  'Financial Services',
  'Food Services (Restaurants/Fast Food)',
  'Gaming',
  'Government',
  'Health Care',
  'Interior Design',
  'Internal',
  'Legal',
  'Manufacturing',
  'Marketing',
  'Mining and Logistics',
  'Non-Profit',
  'Publishing and Web Media',
  'Real Estate',
  'Retail (E-Commerce and Offline)',
  'Services',
  'Technology',
  'Telecommunications',
  'Travel/Hospitality',
  'Web Designing',
  'Web Development',
  'Writers'
];
